version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    container_name: smart-bin-web
    restart: always

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    container_name: ollama-service
    restart: always

volumes:
  ollama_storage:
